---
title: "항공여객수 자동예측"
output:
  word_document: default
  html_notebook: default
---
```{r}
#install.packages("astsa")
#install.packages("fpp")
#install.packages("tidyverse")
```



# 1. 항공여객 데이터셋 ---------------------------------------------------------
```{r}
library(astsa) 
library(fpp)
library(tidyverse)

data("AirPassengers")

ap_ts <- window(AirPassengers, start=1949, end=1958.99)
ap_ts_test <- window(AirPassengers, start=1959)
```

# 1.1. 항공여객 데이터셋 시각화 ---------------------------------------------------------
```{r}
par(mfrow=c(2,1))
par(mar=c(2, 3, 0, 2), xaxs='i', yaxs='i')

plot(ap_ts, ylab="항공여객 (천명)", type="c", pch =20, xaxt='n', xlab="")
text(ap_ts, col=1:12, labels=1:12, cex=.7)

plot(ap_ts, ylab="항공여객 (천명)", type="o", pch =20, xlab="")
```




# 2. 시계열 분해 -----------------------------------------------------------------

# 기본 시계열 분해 :시계열 데이터를 x, trend, seasonal, random 값으로 분해
```{r}
ap_ts_decompM <- decompose(ap_ts, type = "multiplicative")
plot(ap_ts_decompM, xlab="")
```


#관측치, 트랜드, 계절성 , 랜덤 관련 그래프 출력 
# `forecast` 팩키지 계절변동 시각화
```{r}
seasonplot(ap_ts, ylab="항공여객 (천명)", xlab="", 
           main="",
           year.labels=TRUE, year.labels.left=TRUE, col=1:20, pch=19)
```



#월별플롯 
```{r}
monthplot(ap_ts, ylab="항공여객 (천명)", xlab="", xaxt="n", main="")
axis(1, at=1:12, labels=month.abb, cex=0.8)
```


# 3. 모형선정 ------------------------------------------------------------------------
```{r}
models <- list (
  mod_arima = auto.arima(ap_ts, ic='aicc', stepwise=FALSE),
  mod_exponential = ets(ap_ts, ic='aicc', restrict=FALSE),
  mod_neural = nnetar(ap_ts, p=12, size=25),
  mod_tbats = tbats(ap_ts, ic='aicc', seasonal.periods=12),
  mod_bats = bats(ap_ts, ic='aicc', seasonal.periods=12),
  mod_stl = stlm(ap_ts, s.window=12, ic='aicc', robust=TRUE, method='ets'),
  mod_sts = StructTS(ap_ts)
)

forecasts <- lapply(models, forecast, 12)
forecasts$naive <- naive(ap_ts, 12)
```

```{r}

par(mfrow=c(4, 2))
par(mar=c(2, 2, 1.5, 2), xaxs='i', yaxs='i')

for(f in forecasts){
  plot(f, ylim=c(0,600), main="", xaxt="n")
  lines(ap_ts_test, col='red')
}

acc <- lapply(forecasts, function(f){
  accuracy(f, ap_ts_test)[2,,drop=FALSE]
})
```


```{r}
acc <- Reduce(rbind, acc)
row.names(acc) <- names(forecasts)
acc <- acc[order(acc[,'MASE']),]
round(acc, 2)
```



# 4. 모형적합 ------------------------------------------------------------------------
```{r}
ap_tbats_fit <- tbats(ap_ts, ic='aicc', seasonal.periods=12)
plot(ap_tbats_fit)

ap_stl_fit <- stl(ap_ts, s.window = 12)

par(mfrow = c(2,2))
monthplot(ap_ts, ylab = "data", cex.axis = 0.8)
monthplot(ap_stl_fit, choice = "seasonal", cex.axis = 0.8)
monthplot(ap_stl_fit, choice = "trend", cex.axis = 0.8)
monthplot(ap_stl_fit, choice = "remainder", type = "h", cex.axis = 0.8)
```


# 5. 예측 ------------------------------------------------------------------------
# 최적 모형
```{r}
op <- par(mfrow = c(2,1))
par(mar=c(2, 2, 1.5, 2), xaxs='i', yaxs='i')

ap_tbats_fit_fcast <- forecast(ap_tbats_fit)
plot(ap_tbats_fit_fcast, xaxt="n")
mod_sts_fit <- StructTS(ap_ts)
ap_sts_fit_fcast <- forecast(mod_sts_fit)
plot(ap_sts_fit_fcast)
```



